### ISSUE TITLE
autonomous delivery 

### ISSUE THREAD

**Issue by 1MiloAC** [thebestrobotics/OffTheGrid#3]
you didn't put the autonomous delivery coding on GitHub ;[ 👎

**Comment by 1MiloAC** [comment]
plus I fixed the coding look, at pull request it removes the ir sensors but keeps the wheels from drifting  :) 😀😁

**Comment by thebestrobotics** [comment]
I haven't uploaded the encoder code yet because I finally got the base code working quite recently, but the drive distance is incorrect and there's a few other changes I still need to make. I'll try to upload it tomorrow.
Also, check my comment on your last commit.
Thanks for your work!
